# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "blocks", :force => true do |t|
    t.column "street_id", :integer
    t.column "name",      :string
    t.column "sort",      :integer
  end

  create_table "cities", :force => true do |t|
    t.column "created_at", :datetime
    t.column "name",       :string
  end

  create_table "cuisines", :force => true do |t|
    t.column "name", :string
  end

  create_table "cuisines_restaurants", :id => false, :force => true do |t|
    t.column "restaurant_id", :integer
    t.column "cuisine_id",    :integer
  end

  create_table "recommendations", :force => true do |t|
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "user_id",       :integer
    t.column "restaurant_id", :integer
    t.column "recommended",   :integer,  :limit => 4
  end

  create_table "restaurants", :force => true do |t|
    t.column "street_id",  :integer
    t.column "created_at", :datetime
    t.column "name",       :string
    t.column "yelp_url",   :string
    t.column "husky_card", :integer,  :limit => 1
    t.column "coupon_url", :string
    t.column "side",       :string,   :limit => 12
    t.column "delivery",   :integer,  :limit => 1
    t.column "block_id",   :integer
    t.column "top",        :integer
  end

  create_table "streets", :force => true do |t|
    t.column "name",             :string
    t.column "description",      :text
    t.column "created_at",       :datetime
    t.column "url_name",         :string
    t.column "city_id",          :integer
    t.column "neighborhood_url", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "votes", :force => true do |t|
    t.column "ipaddr",     :string
    t.column "candidate",  :string
    t.column "study",      :integer
    t.column "created_at", :datetime
  end

end
